// Copyright (c)2025 Jython Developers.
// Licensed to PSF under a contributor agreement.
package uk.co.farowl.vsj4.core;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.params.provider.Arguments.arguments;

import java.math.BigInteger;
import java.util.stream.Stream;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.junit.jupiter.params.provider.ValueSource;

/**
 * Tests of formatting built-in types to string using their
 * {@code __format__} method (on which built-in method {@code format()}
 * relies).
 * <p>
 * Most of the examples here use values generated by a Python script and
 * placed in a Java array (of {@code Object}). We then create a stream
 * of JUnit arguments objects, each containing those values formatted by
 * a specified format string using the call {@code format(v, fmt)}.
 * <p>
 * A fragment of Python for translating values for the array and
 * arguments object is:<pre>
 * def java_literal(v):
 *     '''Print single value as Java literal'''
 *     if isinstance(v, bool):
 *         return repr(v).lower()
 *     elif isinstance(v, int):
 *         if 2**31 > v >= -2**31:
 *             return repr(v)
 *         else:
 *             return f'new BigInteger("{v!r:s}")'
 *     else: # float
 *         if math.isnan(v):
 *             return 'Double.NaN'
 *         elif math.isinf(v):
 *             if v > 0:
 *                 return 'Double.POSITIVE_INFINITY'
 *             else:
 *                 return 'Double.NEGATIVE_INFINITY'
 *         return repr(v)
 *
 * def gen_example(func_name, values, fmt):
 *     args = '", "'.join(format(v, fmt) for v in values)
 *     return f'{func_name}("{fmt:s}", "{args}"), //'
 * </pre>
 */
class FormatTest extends UnitTestSupport {

    /** Base of tests that format integers. */
    abstract static class AbstractIntFormatTest {

        /**
         * The values corresponding to the expected results in the
         * stream of examples provided by {@link #intExamples()}. In the
         * Python script for generating test data, this array is:<pre>
         * ival = [42, -42, 226, 128013, 2**31-1, -2**31,
         *         False, True, 2**36, -2**36, 7**42]
         * </pre>
         */
        static final Object[] VALUES = {42, -42, 226, 128013,
                2147483647, -2147483648, false, true,
                new BigInteger("68719476736"),
                new BigInteger("-68719476736"),
                new BigInteger("311973482284542371301330321821976049")};

        /**
         * Provide a stream of examples as parameter sets to the tests.
         * In each example, one format has been used to format all the
         * {@link #VALUES}. In the Python script for generating test
         * data, the fragment that generates the test argument sets
         * is:<pre>
         * ifmt = ["d", "o", "x", "X", "b",
         *        ",d", "#o", "#X", "+d", " d",
         *        "5", "^6", "~&lt;5", "0=+6" ]
         *
         * for f in ifmt:
         *     print(gen_example('intExample', ival, f))
         * print(");")
         * </pre>
         *
         * @return the examples for integer formatting tests.
         */
        static Stream<Arguments> intExamples() {
            return Stream.of( //
                    intExample("d", "42", "-42", "226", "128013",
                            "2147483647", "-2147483648", "0", "1",
                            "68719476736", "-68719476736",
                            "311973482284542371301330321821976049"), //
                    intExample("o", "52", "-52", "342", "372015",
                            "17777777777", "-20000000000", "0", "1",
                            "1000000000000", "-1000000000000",
                            "1701257274030155626774437006214073142761"), //
                    intExample("x", "2a", "-2a", "e2", "1f40d",
                            "7fffffff", "-80000000", "0", "1",
                            "1000000000", "-1000000000",
                            "3c157af0306dcb7f23e06460ecc5f1"), //
                    intExample("X", "2A", "-2A", "E2", "1F40D",
                            "7FFFFFFF", "-80000000", "0", "1",
                            "1000000000", "-1000000000",
                            "3C157AF0306DCB7F23E06460ECC5F1"), //
                    intExample("b", "101010", "-101010", "11100010",
                            "11111010000001101",
                            "1111111111111111111111111111111",
                            "-10000000000000000000000000000000", "0",
                            "1",
                            "1000000000000000000000000000000000000",
                            "-1000000000000000000000000000000000000",
                            "1111000001010101111010111100000011000001101101110010110111111100100011111000000110010001100000111011001100010111110001"), //
                    intExample(",d", "42", "-42", "226", "128,013",
                            "2,147,483,647", "-2,147,483,648", "0", "1",
                            "68,719,476,736", "-68,719,476,736",
                            "311,973,482,284,542,371,301,330,321,821,976,049"), //
                    intExample("#o", "0o52", "-0o52", "0o342",
                            "0o372015", "0o17777777777",
                            "-0o20000000000", "0o0", "0o1",
                            "0o1000000000000", "-0o1000000000000",
                            "0o1701257274030155626774437006214073142761"), //
                    intExample("#X", "0X2A", "-0X2A", "0XE2", "0X1F40D",
                            "0X7FFFFFFF", "-0X80000000", "0X0", "0X1",
                            "0X1000000000", "-0X1000000000",
                            "0X3C157AF0306DCB7F23E06460ECC5F1"), //
                    intExample("+d", "+42", "-42", "+226", "+128013",
                            "+2147483647", "-2147483648", "+0", "+1",
                            "+68719476736", "-68719476736",
                            "+311973482284542371301330321821976049"), //
                    intExample(" d", " 42", "-42", " 226", " 128013",
                            " 2147483647", "-2147483648", " 0", " 1",
                            " 68719476736", "-68719476736",
                            " 311973482284542371301330321821976049"), //
                    intExample("5", "   42", "  -42", "  226", "128013",
                            "2147483647", "-2147483648", "    0",
                            "    1", "68719476736", "-68719476736",
                            "311973482284542371301330321821976049"), //
                    intExample("^6", "  42  ", " -42  ", " 226  ",
                            "128013", "2147483647", "-2147483648",
                            "  0   ", "  1   ", "68719476736",
                            "-68719476736",
                            "311973482284542371301330321821976049"), //
                    intExample("~<5", "42~~~", "-42~~", "226~~",
                            "128013", "2147483647", "-2147483648",
                            "0~~~~", "1~~~~", "68719476736",
                            "-68719476736",
                            "311973482284542371301330321821976049"), //
                    intExample("0=+6", "+00042", "-00042", "+00226",
                            "+128013", "+2147483647", "-2147483648",
                            "+00000", "+00001", "+68719476736",
                            "-68719476736",
                            "+311973482284542371301330321821976049"), //

                    // char formats (hand-crafted) --------------------
                    intExample("c", new Object[] {42, 226, 128013}, //
                            "*", "â", "🐍"));
        }

        /**
         * Construct a set of test arguments for a single format type
         * and a reference result for each value in {@link #VALUES},
         * provided by the caller. We convert reference results to
         * {@code PyUnicode} to ensure we get Python comparison
         * semantics.
         *
         * @param format to apply
         * @param expected results to expect
         * @return example data for a test
         */
        private static Arguments intExample(String format,
                String... expected) {
            return intExample(format, VALUES, expected);
        }

        /**
         * Construct a set of test arguments for a single format type
         * and a reference result for each value in {@code values},
         * provided by the caller. We convert reference results to
         * {@code PyUnicode} to ensure we get Python comparison
         * semantics.
         *
         * @param format to apply
         * @param values to apply {@code format} to
         * @param expected results to expect
         * @return example data for a test
         */
        private static Arguments intExample(String format,
                Object[] values, String... expected) {
            assert expected.length == values.length;
            PyUnicode[] uExpected = new PyUnicode[expected.length];
            for (int i = 0; i < expected.length; i++) {
                uExpected[i] = newPyUnicode(expected[i]);
            }
            return arguments(format, values, uExpected);
        }
    }

    /**
     * Test formatting an integer
     */
    @Disabled("int.__format__ not yet implemented")
    @Nested
    @DisplayName("int.__format__")
    class IntFormatTest extends AbstractIntFormatTest {

        @DisplayName("int.__format__(int, String)")
        @ParameterizedTest(name = "int.__format__(x, \"{0}\")")
        @MethodSource("intExamples")
        void intFormat(String format, Object[] values,
                PyUnicode[] expected) {
            for (int i = 0; i < values.length; i++) {
                Object r = PyLong.__format__(values[i], format);
                assertEquals(expected[i], r);
            }
        }

        @DisplayName("int.__format__: unknown specifier")
        @ParameterizedTest(name = "int.__format__(x, \"{0}\")")
        @ValueSource(strings = {"z", "#10z"})
        void intFormatUnknown(String format) {
            assertRaises(PyExc.ValueError,
                    () -> PyLong.__format__(0, format),
                    "Unknown format code 'z' for object of type 'int'");
        }

        @DisplayName("int.__format__: precision not allowed")
        @ParameterizedTest(name = "int.__format__(x, \"{0}\")")
        @ValueSource(strings = {"123.456x", ".5d", "0=+6.1"})
        void intFormatWithPrecision(String format) {
            assertRaises(PyExc.ValueError,
                    () -> PyLong.__format__(0, format),
                    "Precision not allowed in integer format specifier");
        }

        @DisplayName("int.__format__: grouping not allowed")
        @ParameterizedTest(name = "int.__format__(x, \"{0}\")")
        @ValueSource(strings = {"10,n", ",n"})
        void intFormatNWithGrouping(String format) {
            assertRaises(PyExc.ValueError,
                    () -> PyLong.__format__(0, format),
                    // CPython: "Cannot specify ',' with 'n'");
                    // But we prefer:
                    "Grouping (,) not allowed with integer format specifier 'n'");
        }

        @DisplayName("int.__format__: sign not allowed")
        @ParameterizedTest(name = "int.__format__(x, \"{0}\")")
        @ValueSource(strings = {"+c", "-c", "+10c"})
        void intFormatCWithSign(String format) {
            assertRaises(PyExc.ValueError,
                    () -> PyLong.__format__(0, format),
                    "Sign not allowed with integer format specifier 'c'");
        }

        @DisplayName("int.__format__: alternate form not allowed")
        @ParameterizedTest(name = "int.__format__(x, \"{0}\")")
        @ValueSource(strings = {"#c", "#10c"})
        void intFormatCWithAltForm(String format) {
            assertRaises(PyExc.ValueError,
                    () -> PyLong.__format__(0, format),
                    "Alternate form (#) not allowed with integer format specifier 'c'");
        }
    }

    /** Base of tests that format floats. */
    abstract static class AbstractFloatFormatTest {

        /**
         * The values corresponding to the expected results in the
         * stream of examples provided by {@link #floatExamples()}. In
         * the Python script for generating test data, this array
         * is:<pre>
         * fval = [42., -42., -22.75, 128.005, 1.23456789,
         *         -1234567890000000., 0.00012345,
         *         -1.2345e-30, 1.2344e-30, math.inf, math.nan]
         * </pre>
         */
        static final Object[] VALUES = {42.0, -42.0, -22.75, 128.005,
                1.23456789, -1234567890000000.0, 0.00012345,
                -1.2345e-30, 1.2344e-30, Double.POSITIVE_INFINITY,
                Double.NaN};

        /**
         * Provide a stream of examples as parameter sets to the tests.
         * In each example, one format has been used to format all the
         * {@link #VALUES}. In the Python script for generating test
         * data, the fragment that generates the test argument sets
         * is:<pre>
         * ffmt = ["f", "8.3f", "12f", "0.2f", "+6.1F",
         *         "<15.1f", "^15.1f", ">15.1F",
         *         "~<15.1f", "~^15.1F", "~>15.1f",
         *         "g", "8.3g", "12g", "0.2g", "+6.1G",
         *         "<15.1g", "^15.1g", ">15.1G",
         *         "~<15.1g", "~^15.1G", "~>15.1g",
         *         "e", "8.3e", "12e", "0.2e", "+6.1E",
         *         "<15.1e", "^15.1e", ">15.1E",
         *         "~<15.1e", "~^15.1E", "~>15.1e"]
         *
         * for f in ffmt:
         *     print(gen_example('floatExample', fval, f))
         * print(");")
         * </pre>
         *
         * @return the examples for integer formatting tests.
         */
        static Stream<Arguments> floatExamples() {
            return Stream.of( //
                    floatExample("f", "42.000000", "-42.000000",
                            "-22.750000", "128.005000", "1.234568",
                            "-1234567890000000.000000", "0.000123",
                            "-0.000000", "0.000000", "inf", "nan"), //
                    floatExample("8.3f", "  42.000", " -42.000",
                            " -22.750", " 128.005", "   1.235",
                            "-1234567890000000.000", "   0.000",
                            "  -0.000", "   0.000", "     inf",
                            "     nan"), //
                    floatExample("12f", "   42.000000", "  -42.000000",
                            "  -22.750000", "  128.005000",
                            "    1.234568", "-1234567890000000.000000",
                            "    0.000123", "   -0.000000",
                            "    0.000000", "         inf",
                            "         nan"), //
                    floatExample("0.2f", "42.00", "-42.00", "-22.75",
                            "128.00", "1.23", "-1234567890000000.00",
                            "0.00", "-0.00", "0.00", "inf", "nan"), //
                    floatExample("+6.1F", " +42.0", " -42.0", " -22.8",
                            "+128.0", "  +1.2", "-1234567890000000.0",
                            "  +0.0", "  -0.0", "  +0.0", "  +INF",
                            "  +NAN"), //
                    floatExample("<15.1f", "42.0           ",
                            "-42.0          ", "-22.8          ",
                            "128.0          ", "1.2            ",
                            "-1234567890000000.0", "0.0            ",
                            "-0.0           ", "0.0            ",
                            "inf            ", "nan            "), //
                    floatExample("^15.1f", "     42.0      ",
                            "     -42.0     ", "     -22.8     ",
                            "     128.0     ", "      1.2      ",
                            "-1234567890000000.0", "      0.0      ",
                            "     -0.0      ", "      0.0      ",
                            "      inf      ", "      nan      "), //
                    floatExample(">15.1F", "           42.0",
                            "          -42.0", "          -22.8",
                            "          128.0", "            1.2",
                            "-1234567890000000.0", "            0.0",
                            "           -0.0", "            0.0",
                            "            INF", "            NAN"), //
                    floatExample("~<15.1f", "42.0~~~~~~~~~~~",
                            "-42.0~~~~~~~~~~", "-22.8~~~~~~~~~~",
                            "128.0~~~~~~~~~~", "1.2~~~~~~~~~~~~",
                            "-1234567890000000.0", "0.0~~~~~~~~~~~~",
                            "-0.0~~~~~~~~~~~", "0.0~~~~~~~~~~~~",
                            "inf~~~~~~~~~~~~", "nan~~~~~~~~~~~~"), //
                    floatExample("~^15.1F", "~~~~~42.0~~~~~~",
                            "~~~~~-42.0~~~~~", "~~~~~-22.8~~~~~",
                            "~~~~~128.0~~~~~", "~~~~~~1.2~~~~~~",
                            "-1234567890000000.0", "~~~~~~0.0~~~~~~",
                            "~~~~~-0.0~~~~~~", "~~~~~~0.0~~~~~~",
                            "~~~~~~INF~~~~~~", "~~~~~~NAN~~~~~~"), //
                    floatExample("~>15.1f", "~~~~~~~~~~~42.0",
                            "~~~~~~~~~~-42.0", "~~~~~~~~~~-22.8",
                            "~~~~~~~~~~128.0", "~~~~~~~~~~~~1.2",
                            "-1234567890000000.0", "~~~~~~~~~~~~0.0",
                            "~~~~~~~~~~~-0.0", "~~~~~~~~~~~~0.0",
                            "~~~~~~~~~~~~inf", "~~~~~~~~~~~~nan"), //
                    floatExample("g", "42", "-42", "-22.75", "128.005",
                            "1.23457", "-1.23457e+15", "0.00012345",
                            "-1.2345e-30", "1.2344e-30", "inf", "nan"), //
                    floatExample("8.3g", "      42", "     -42",
                            "   -22.8", "     128", "    1.23",
                            "-1.23e+15", "0.000123", "-1.23e-30",
                            "1.23e-30", "     inf", "     nan"), //
                    floatExample("12g", "          42", "         -42",
                            "      -22.75", "     128.005",
                            "     1.23457", "-1.23457e+15",
                            "  0.00012345", " -1.2345e-30",
                            "  1.2344e-30", "         inf",
                            "         nan"), //
                    floatExample("0.2g", "42", "-42", "-23", "1.3e+02",
                            "1.2", "-1.2e+15", "0.00012", "-1.2e-30",
                            "1.2e-30", "inf", "nan"), //
                    floatExample("+6.1G", "+4E+01", "-4E+01", "-2E+01",
                            "+1E+02", "    +1", "-1E+15", "+0.0001",
                            "-1E-30", "+1E-30", "  +INF", "  +NAN"), //
                    floatExample("<15.1g", "4e+01          ",
                            "-4e+01         ", "-2e+01         ",
                            "1e+02          ", "1              ",
                            "-1e+15         ", "0.0001         ",
                            "-1e-30         ", "1e-30          ",
                            "inf            ", "nan            "), //
                    floatExample("^15.1g", "     4e+01     ",
                            "    -4e+01     ", "    -2e+01     ",
                            "     1e+02     ", "       1       ",
                            "    -1e+15     ", "    0.0001     ",
                            "    -1e-30     ", "     1e-30     ",
                            "      inf      ", "      nan      "), //
                    floatExample(">15.1G", "          4E+01",
                            "         -4E+01", "         -2E+01",
                            "          1E+02", "              1",
                            "         -1E+15", "         0.0001",
                            "         -1E-30", "          1E-30",
                            "            INF", "            NAN"), //
                    floatExample("~<15.1g", "4e+01~~~~~~~~~~",
                            "-4e+01~~~~~~~~~", "-2e+01~~~~~~~~~",
                            "1e+02~~~~~~~~~~", "1~~~~~~~~~~~~~~",
                            "-1e+15~~~~~~~~~", "0.0001~~~~~~~~~",
                            "-1e-30~~~~~~~~~", "1e-30~~~~~~~~~~",
                            "inf~~~~~~~~~~~~", "nan~~~~~~~~~~~~"), //
                    floatExample("~^15.1G", "~~~~~4E+01~~~~~",
                            "~~~~-4E+01~~~~~", "~~~~-2E+01~~~~~",
                            "~~~~~1E+02~~~~~", "~~~~~~~1~~~~~~~",
                            "~~~~-1E+15~~~~~", "~~~~0.0001~~~~~",
                            "~~~~-1E-30~~~~~", "~~~~~1E-30~~~~~",
                            "~~~~~~INF~~~~~~", "~~~~~~NAN~~~~~~"), //
                    floatExample("~>15.1g", "~~~~~~~~~~4e+01",
                            "~~~~~~~~~-4e+01", "~~~~~~~~~-2e+01",
                            "~~~~~~~~~~1e+02", "~~~~~~~~~~~~~~1",
                            "~~~~~~~~~-1e+15", "~~~~~~~~~0.0001",
                            "~~~~~~~~~-1e-30", "~~~~~~~~~~1e-30",
                            "~~~~~~~~~~~~inf", "~~~~~~~~~~~~nan"), //
                    floatExample("e", "4.200000e+01", "-4.200000e+01",
                            "-2.275000e+01", "1.280050e+02",
                            "1.234568e+00", "-1.234568e+15",
                            "1.234500e-04", "-1.234500e-30",
                            "1.234400e-30", "inf", "nan"), //
                    floatExample("8.3e", "4.200e+01", "-4.200e+01",
                            "-2.275e+01", "1.280e+02", "1.235e+00",
                            "-1.235e+15", "1.234e-04", "-1.235e-30",
                            "1.234e-30", "     inf", "     nan"), //
                    floatExample("12e", "4.200000e+01", "-4.200000e+01",
                            "-2.275000e+01", "1.280050e+02",
                            "1.234568e+00", "-1.234568e+15",
                            "1.234500e-04", "-1.234500e-30",
                            "1.234400e-30", "         inf",
                            "         nan"), //
                    floatExample("0.2e", "4.20e+01", "-4.20e+01",
                            "-2.28e+01", "1.28e+02", "1.23e+00",
                            "-1.23e+15", "1.23e-04", "-1.23e-30",
                            "1.23e-30", "inf", "nan"), //
                    floatExample("+6.1E", "+4.2E+01", "-4.2E+01",
                            "-2.3E+01", "+1.3E+02", "+1.2E+00",
                            "-1.2E+15", "+1.2E-04", "-1.2E-30",
                            "+1.2E-30", "  +INF", "  +NAN"), //
                    floatExample("<15.1e", "4.2e+01        ",
                            "-4.2e+01       ", "-2.3e+01       ",
                            "1.3e+02        ", "1.2e+00        ",
                            "-1.2e+15       ", "1.2e-04        ",
                            "-1.2e-30       ", "1.2e-30        ",
                            "inf            ", "nan            "), //
                    floatExample("^15.1e", "    4.2e+01    ",
                            "   -4.2e+01    ", "   -2.3e+01    ",
                            "    1.3e+02    ", "    1.2e+00    ",
                            "   -1.2e+15    ", "    1.2e-04    ",
                            "   -1.2e-30    ", "    1.2e-30    ",
                            "      inf      ", "      nan      "), //
                    floatExample(">15.1E", "        4.2E+01",
                            "       -4.2E+01", "       -2.3E+01",
                            "        1.3E+02", "        1.2E+00",
                            "       -1.2E+15", "        1.2E-04",
                            "       -1.2E-30", "        1.2E-30",
                            "            INF", "            NAN"), //
                    floatExample("~<15.1e", "4.2e+01~~~~~~~~",
                            "-4.2e+01~~~~~~~", "-2.3e+01~~~~~~~",
                            "1.3e+02~~~~~~~~", "1.2e+00~~~~~~~~",
                            "-1.2e+15~~~~~~~", "1.2e-04~~~~~~~~",
                            "-1.2e-30~~~~~~~", "1.2e-30~~~~~~~~",
                            "inf~~~~~~~~~~~~", "nan~~~~~~~~~~~~"), //
                    floatExample("~^15.1E", "~~~~4.2E+01~~~~",
                            "~~~-4.2E+01~~~~", "~~~-2.3E+01~~~~",
                            "~~~~1.3E+02~~~~", "~~~~1.2E+00~~~~",
                            "~~~-1.2E+15~~~~", "~~~~1.2E-04~~~~",
                            "~~~-1.2E-30~~~~", "~~~~1.2E-30~~~~",
                            "~~~~~~INF~~~~~~", "~~~~~~NAN~~~~~~"), //
                    floatExample("~>15.1e", "~~~~~~~~4.2e+01",
                            "~~~~~~~-4.2e+01", "~~~~~~~-2.3e+01",
                            "~~~~~~~~1.3e+02", "~~~~~~~~1.2e+00",
                            "~~~~~~~-1.2e+15", "~~~~~~~~1.2e-04",
                            "~~~~~~~-1.2e-30", "~~~~~~~~1.2e-30",
                            "~~~~~~~~~~~~inf", "~~~~~~~~~~~~nan") //
            );
        }

        /**
         * Construct a set of test arguments for a single format type
         * and a reference result for each value in {@link #VALUES},
         * provided by the caller. We convert reference results to
         * {@code PyUnicode} to ensure we get Python comparison
         * semantics.
         *
         * @param format to apply
         * @param expected results to expect
         * @return example data for a test
         */
        private static Arguments floatExample(String format,
                String... expected) {
            return floatExample(format, VALUES, expected);
        }

        /**
         * Construct a set of test arguments for a single format type
         * and a reference result for each value in {@code values},
         * provided by the caller. We convert reference results to
         * {@code PyUnicode} to ensure we get Python comparison
         * semantics.
         *
         * @param format to apply
         * @param values to apply {@code format} to
         * @param expected results to expect
         * @return example data for a test
         */
        private static Arguments floatExample(String format,
                Object[] values, String... expected) {
            assert expected.length == values.length;
            PyUnicode[] uExpected = new PyUnicode[expected.length];
            for (int i = 0; i < expected.length; i++) {
                uExpected[i] = newPyUnicode(expected[i]);
            }
            return arguments(format, values, uExpected);
        }
    }

    /**
     * Test formatting an float
     */
    @Nested
    @DisplayName("float.__format__")
    class FloatFormatTest extends AbstractFloatFormatTest {

        @DisplayName("float.__format__(float, String)")
        @ParameterizedTest(name = "float.__format__(x, \"{0}\")")
        @MethodSource("floatExamples")
        void floatFormat(String format, Object[] values,
                PyUnicode[] expected) {
            for (int i = 0; i < values.length; i++) {
                Object r = PyFloat.__format__(values[i], format);
                assertEquals(expected[i], r);
            }
        }

    }

    @Disabled("str.__format__ not yet implemented")
    @Test
    @DisplayName("rudimentary str.__format__ test")
    @SuppressWarnings("static-method")
    void strFormat() {
        String v = "abc";
        PyUnicode e = newPyUnicode(v);
        Object r = PyUnicode.__format__(v, "");
        assertEquals(e, r);

        String v2 = "abcdef";
        r = PyUnicode.__format__(v2, ".3");
        assertEquals(e, r);

        r = PyUnicode.__format__(v2, "6");
        PyUnicode e2 = newPyUnicode("abc ");
        assertEquals(e2, r);
    }
}
