#! /usr/bin/env python3
"""
Generate Java code from an ASDL description.

The code is based on asdl_c.py but has been made specific to Java,
first in Tobias Kohn's Java-pegen project, and later here for use
in Jython.
"""

from argparse import ArgumentParser
from typing import Callable, Optional
from pathlib import Path
import re

import sys

import asdl

from codegen.javagen import (
    JavaClass,
    JavaPseudoEnum,
    JavaField,
    JavaVisitor,
    JavaVisitorInterface,
    default_value_for_java_type,
    to_java_name,
)

from codegen.cache import CodeTranslationCache, function_encoder, function_decoder

CORE_PACKAGE = 'org.python.core'  # --core-package option default
# --ast-package option supersedes
AST_PACKAGE = 'org.python.internal.ast'
BASE_TYPE = 'AST'  # all non-enum AST classes extend this class
OUTPUT_DIR = 'build/generated/sources/pegen/java/main'  # --output-dir default


class AsdlJavaContext:
    """Context for Java code generation (in asdl_java)

    An instance holds a root path for the generated Java files,
    plus the package names needed to read or create those files.
    """

    def __init__(self, dest_path: Path,
                 core_package: str, ast_package: str, base_type: str,
                 input_maps: Path, output_maps: Path,
                 generator: str):
        """Create context for Java code generation

        This configures the process of converting ASDL to Java AST
        types and a subsequent compiler-generator process, with
        package locations and code generation apparatus.

        It also specifies where to place metadata that is useful in
        correlating names in CPython with names in the generated
        Java. That information is important for translating actions
        written in C (the actions in Python.gram) to Java, perhaps
        mechanically, if it could be done reliably.

        Args:
            dest_path (Path): Path for the generated code directory
                Java files are placed at dest_path / java / package
            core_package (string): package name of Jython core classes
            ast_package (string): package name of AST classes
            base_type (string): name of base class of AST classes
            input_maps (Path): location (directory) of C-Java maps to read
            output_maps (Path): path to C-Java maps to write
            generator (string): a string from which to deduce the tool
                used to create files. Usually __file__ will do.
        """
        self.dest_path = dest_path
        self.core_package = core_package
        self.ast_package = ast_package
        self.base_type = base_type
        self.generator = AsdlJavaContext._generator_name(generator)
        self._ast_path = None  # meaning not computed/created
        # NamingVisitor initialises C-Java maps from files here:
        self.input_maps = input_maps
        # NamingVisitor writes files here to assist semi-mechanical translation:
        self.output_maps = output_maps
        # NamingVisitor fills and StructVisitor uses:
        self.asdl_java_map: dict[str, str]

    @staticmethod
    def _generator_name(generator: Optional[str]) -> Optional[str]:
        """Deduce short name for program/module from path (e.g. __file__)

        This gets used in the "generated by ..." comment of the code. The
        short name is a path, including the containing package names,
        relative to the library that apparently contains it.
        """
        if generator:
            try:
                path = Path(generator).resolve()  # in full
                if path.stem == '__main__':
                    # tool is __main__ of package: use package
                    path = path.parent
                # will compute containing library
                location = path.parent
                while (location / '__init__.py').exists():
                    location = location.parent
                path = path.relative_to(location)
                return '/'.join(path.with_suffix('').parts)
            except FileNotFoundError:
                # Assume a non-file name is being used
                return generator
        else:
            return None

    def get_package_path(self) -> Path:
        """Get path for AST generated source directory (and create)"""
        if not self._ast_path:
            self._ast_path = self.dest_path.joinpath(
                *self.ast_package.split('.'))
            self._ast_path.mkdir(parents=True, exist_ok=True)
        return self._ast_path

# Several functions from asdl_c.py that relate to C-code generation.
# These support the EmitVisitor, which needs to be re-written, but
# we also find C-names useful for mapping purposes.


TABSIZE = 4
MAX_COL = 80
AUTOGEN_MESSAGE = "// File automatically generated by {}.\n\n"


def get_c_type(name):
    """Return a string for the C name of the type.

    This function special cases the default types provided by asdl.
    """
    if name in asdl.builtin_types:
        return name
    else:
        return "%s_ty" % name


def is_simple(sum_type):
    """Return True if a sum is simple.

    A sum is simple if its types have no fields and the sum itself
    has no attributes. The sum type is mapped to an enum in Java.
    Instances are the values of the enum and are singletons when
    propagated to the Python level in the _ast module, e.g.
    unaryop = Invert | Not | UAdd | USub
    """

    return not (
        sum_type.attributes or
        any(constructor.fields for constructor in sum_type.types)
    )



class NamingVisitor(asdl.VisitorBase):
    """
    Visitor to survey the names used in AST elements in C and Java.

    We survey the types defined (and constructor names), to
    ensure we encounter them before the fields or attributes that
    may use these types.
    """

    # ASDL's 4 built in types are: identifier, string, int, and constant
    _ASDL_JAVA_TYPE = dict(
        identifier='String',
        string='String',
        int='int',
        constant='Object',
    )
    assert set(_ASDL_JAVA_TYPE.keys()) == set(asdl.builtin_types)

    def __init__(self, context: AsdlJavaContext):
        super().__init__()
        self.context = context
        # Map name in Python.asdl to Java type (primitive, class or enum)
        self.asdl_map = context.asdl_java_map = dict(
            NamingVisitor._ASDL_JAVA_TYPE)
        # Translation helpers from CPython to Java (e.g. in actions):
        self.translations = CodeTranslationCache('types', 'exprs',
                                                 cache_file_suffix=".c_java_map")
        self.translations.add_map('functions', encoder=function_encoder, decoder=function_decoder)
        
        #self.translations.load(self.context.input_maps)
        self.type_map = self.translations.types
        self.expr_map = self.translations.exprs
        self.function_map = self.translations.functions


    def add_asdl(self, asdl_name: str, java_name: str):
        self.asdl_map[asdl_name] = java_name

    def add_type(self, c_name: str, java_name: str):
        self.type_map[c_name] = java_name

    def add_expr(self, c_expr: str, java_expr: str):
        self.expr_map[c_expr] = java_expr

    def add_function(self, c_name: str, c_args: dict[str, str], java_name: str, java_args: dict[str, str]):
        self.function_map[c_name] = (c_args, java_name, java_args)

    def visitModule(self, mod: asdl.Module):
        for dfn in mod.dfns:
            self.visit(dfn)

    def visitType(self, t: asdl.Type):
        self.visit(t.value, t.name)

    def visitSum(self, sum: asdl.Sum, name: str):
        if is_enum := is_simple(sum):
            # The sum is represented by an enum. "Constructors" are constants.
            java_name = to_java_name(
                name, prefix='_', start_with_upper=True)
        else:
            # The sum is represented by an abstract class.
            java_name = to_java_name(
                name, prefix='AST', start_with_upper=True)
        self.add_asdl(name, java_name)
        # CPython has a corresponding type name_ty
        self.add_type(f'{name}_ty', java_name)
        # Find the names of concrete sub-types or enum constants.
        for cons in sum.types:
            self.visit(cons, is_enum, java_name)

    def visitConstructor(self, cons: asdl.Constructor, is_enum: bool, qualifier: str):
        name = cons.name
        java_name = to_java_name(name)
        # TODO Java class (c|sh)ould be nested and name qualified
        self.add_asdl(name, java_name)
        if is_enum:
            # CPython has an enum constant called name, that in Java
            # is also an enum constant scoped by the qualifier.
            self.add_expr(name, f'{qualifier}.{java_name}')
        else:
            # CPython has a factory _PyAST_name returning name_ty,
            # that in Java becomes a constructor call.
            self.add_function(f'_PyAST_{name}', {}, f'AST.{java_name}', {})

    def visitProduct(self, product: asdl.Product, name: str):
        # A product is represented by a concrete (non-nested) class
        java_name = to_java_name(name, start_with_upper=True)
        self.add_asdl(name, java_name)
        # CPython has a corresponding type name_ty
        self.add_type(f'{name}_ty', java_name)
        # CPython has a factory returning name_ty called:
        self.add_function(f'_PyAST_{name}', {}, f'AST.{java_name}', {})

class StructVisitor(asdl.VisitorBase):
    """
    Visitor to generate classes and enums for the AST.

    This relies on a mapping of the names of ASDL types to Java,
    that has been stored in the context object by a NamingVisitor.
    """

    def __init__(self, context: AsdlJavaContext):
        super().__init__()
        self.context = context
        self.package = context.ast_package
        self.cls_stack = [context.base_type]
        self.default_visitor = JavaVisitor("ASTDefaultVisitor", base_cls=None,
                                           package=self.package, modifiers=['public'])
        self.visitor_stack = [(self.cls_stack[0], self.default_visitor)]
        self.java_classes = [self.default_visitor]

    def write_java_classes(self):
        """
        Writes all generated Java-classes to disk.
        """
        ctx = self.context
        path = ctx.get_package_path()
        generator = ctx.generator
        for jc in self.java_classes:
            jc.save_to_file(path, generator)

    def begin_class(self, name: str,
                    cls_type: Callable[..., JavaClass] = JavaClass,
                    create_visitor: bool = False):
        base_cls = self.cls_stack[-1]
        cls = cls_type(name, base_cls=base_cls,
                       package=self.package, modifiers=['public'])
        self.cls_stack.append(cls)
        self.java_classes.append(cls)
        if cls.visitable:
            for (_, visitor) in self.visitor_stack:
                visitor.add_visit_method(cls)
        if create_visitor:
            iface = JavaVisitorInterface(name + 'Visitor',
                                         package=self.package)
            self.visitor_stack.append((cls, iface))
            self.java_classes.append(iface)
            # The default visitor implements this interface too
            self.default_visitor.add_interface(iface)
        return cls

    def end_class(self):
        cls = self.cls_stack.pop()
        if self.visitor_stack and self.visitor_stack[-1][0] == cls:
            self.visitor_stack.pop()

    def get_java_type(self, asdl_type_name: str, is_seq: bool = False) -> str:
        """Map an ASDL type to its Java type"""
        if is_seq:
            # or PyList ?
            return self.get_java_type(asdl_type_name) + '[]'
        return self.context.asdl_java_map[asdl_type_name]

    @property
    def current_class(self):
        return self.cls_stack[-1]

    def visitModule(self, mod):
        for dfn in mod.dfns:
            self.visit(dfn)

    def visitType(self, type):
        self.visit(type.value, type.name)

    def visitSum(self, sum, asdl_name):
        if is_simple(sum):
            self.sum_as_enum(sum, asdl_name)
        else:
            self.sum_with_constructors(sum, asdl_name)

    def sum_as_enum(self, sum, asdl_name):
        java_name = self.get_java_type(asdl_name)
        cls = self.begin_class(java_name, JavaPseudoEnum)
        for field in sum.types:
            cls.add(field.name)
        self.end_class()

    def sum_with_constructors(self, sum, asdl_name):
        java_name = self.get_java_type(asdl_name)
        cls = self.begin_class(java_name, JavaClass, True)
        for field in sum.attributes:
            type = self.get_java_type(field.type)
            init = default_value_for_java_type(type)
            cls.add(JavaField(field.name, type, init))
        for t in sum.types:
            self.visit(t)
        self.end_class()

    def visitConstructor(self, cons):
        cls = self.begin_class(self.get_java_type(cons.name))
        for field in cons.fields:
            self.visit(field)
        self.end_class()

    def visitField(self, field):
        java_type = self.get_java_type(field.type, field.seq)
        self.current_class.add(
            JavaField(field.name, java_type, is_optional=field.opt))

    def visitProduct(self, product, asdl_name):
        cls = self.begin_class(self.get_java_type(asdl_name))
        for field in product.fields:
            self.visit(field)
        for field in product.attributes:
            # rudimentary attribute handling
            type = self.get_java_type(field.type)
            assert type in asdl.builtin_types, type
            cls.add(JavaField(field.name, type))
        self.end_class()


def write_source(context: AsdlJavaContext, mod):
    v = StructVisitor(context)
    v.visit(mod)
    v.write_java_classes()
    print("Output written to", context.get_package_path())


def main(context: AsdlJavaContext, input_file: str, dump_module=False):

    # Build an AST of the ASDL that describes the AST of the language.
    mod = asdl.parse(input_file)
    if dump_module:
        print('Parsed Module:')
        print(mod)
    if not asdl.check(mod):
        sys.exit(1)

    # Gather the names of data types and their translations to Java.
    # We do this before we encounter them as field types.
    names = NamingVisitor(context)
    names.translations.load(context.input_maps)
    names.visit(mod)

    # Write java_type_converter global dictionary with C-Java map.
    names.translations.save(context.output_maps)

    # Walk the tree generating Java classes for the types it defines.
    # These are the AST classes we use in the parser.
    write_source(context, mod)


if __name__ == "__main__":
    prog_dir = Path(__file__).parent
    parser = ArgumentParser()
    parser.add_argument("input_file", type=Path, nargs='?',
                        default=Path(__file__).with_name('Python.asdl'),
                        help="ASDL defining the nodes (default: built-in Python.asdl)")
    parser.add_argument("output_dir", type=Path, nargs='?',
                        default=Path.cwd().joinpath(*OUTPUT_DIR.split('/')),
                        help=f"output directory for generated code (default: {OUTPUT_DIR})")
    parser.add_argument("-a", "--ast-package", default=AST_PACKAGE,
                        help=f"AST Java package name (default: {AST_PACKAGE})")
    parser.add_argument("-b", "--base-type",
                        default=BASE_TYPE,
                        help=f"Base class name in AST package (default: {BASE_TYPE})")
    parser.add_argument("-c", "--core-package",
                        default=CORE_PACKAGE,
                        help=f"Core Jython package name (default: {CORE_PACKAGE})")
    parser.add_argument("-m", "--input-maps", type=Path,
                        default=None,
                        help="Location of C-Java maps to read (default: same as input_file)")
    parser.add_argument("-d", "--dump-module", action="store_true")

    args = parser.parse_args()

    if args.input_maps is None and args.input_file.exists():
        args.input_maps = args.input_file.parent

    main(AsdlJavaContext(
        args.output_dir,
        args.core_package,
        args.ast_package,
        args.base_type,
        args.input_maps,
        args.output_dir,
        __file__
    ),
        args.input_file,
        args.dump_module)
