#! /usr/bin/env python
"""
Generate Java code from an ASDL description.

The code is based on asdl_c.py but has been made specific to Java, first in
Tobias Kohn's Java-pegen project, and later here for use in Jython.
"""
import os
import sys
import textwrap
import types


from typing import Optional, Callable

import asdl

from argparse import ArgumentParser
from pathlib import Path
from codegen.javagen import (
    JavaClass,
    JavaPseudoEnum,
    JavaVariable,
    JavaVisitor,
    JavaVisitorInterface,
    default_value_for_j_type,
    to_java_name,
)

CORE_PACKAGE = 'org.python.core'  # --core-package option default
AST_PACKAGE = 'org.python.internal.ast'  # --ast-package option supersedes
BASE_TYPE = 'AST'  # all AST classes extend this class
OUTPUT_DIR = 'build/generated/sources/pegen/java/main'  # --output-dir default

class AsdlJavaContext:
    """Context for Java code generation (in asdl_java)

    An instance holds a root path for the generated Java files,
    plus the package names needed to read or create those files.
    """
    def __init__(self, dest_path: Path,
                 core_package: str, ast_package: str, base_type: str,
                 c_java_map: Path,
                 generator: str):
        """Create context for Java code generation

        Args:
            dest_path (Path): Path for the generated code directory
                Java files are placed at dest_path / java / package
            core_package (string): package name of Jython core classes
            ast_package (string): package name of AST classes
            base_type (string): name of base class of AST classes
            type_map (Path): path to C-Java type map to write/update
            generator (string): tool being used to create files.
                Usually __file__ will do.
        """
        self.dest_path = dest_path
        self.core_package = core_package
        self.ast_package = ast_package
        self.base_type = base_type
        self.generator = AsdlJavaContext._generator_name(generator)
        self._ast_path = None  # meaning not computed/created
        # NamingVisitor fills to assist semi-mechanical translation:
        self.c_java_map = c_java_map
        # NamingVisitor fills and StructVisitor uses:
        self.asdl_java_map: dict[str, str]

    @staticmethod
    def _generator_name(generator: Optional[str]) -> Optional[str]:
        """Deduce short name for program/module from path (e.g. __file__)
        
        This gets used in the "generated by ..." comment of the code. The
        short name is a path, including the containing package names,
        relative to the library that apparently contains it.
        """
        if generator:
            try:
                path = Path(generator).resolve() # in full
                if path.stem == '__main__':
                    # tool is __main__ of package: use package
                    path = path.parent
                # will compute containing library
                location = path.parent
                while (location / '__init__.py').exists():
                    location = location.parent
                path = path.relative_to(location)
                return '/'.join(path.with_suffix('').parts)
            except FileNotFoundError:
                # Assume a non-file name is being used
                return generator
        else:
            return None

    def get_package_path(self) -> Path:
        """Get path for AST generated source directory (and create)"""
        if not self._ast_path:
            self._ast_path = self.dest_path.joinpath(
                *self.ast_package.split('.'))
            self._ast_path.mkdir(parents=True, exist_ok=True)
        return self._ast_path

# Several functions from asdl_c.py that relate to C-code generation.
# These support the EmitVisitor, which needs to be re-written, but
# we also find C-names useful for mapping purposes.

TABSIZE = 4
MAX_COL = 80
AUTOGEN_MESSAGE = "// File automatically generated by {}.\n\n"

def get_c_type(name):
    """Return a string for the C name of the type.

    This function special cases the default types provided by asdl.
    """
    if name in asdl.builtin_types:
        return name
    else:
        return "%s_ty" % name

def reflow_lines(s, depth):
    """Reflow the line s indented depth tabs.

    Return a sequence of lines where no line extends beyond MAX_COL
    when properly indented.  The first line is properly indented based
    exclusively on depth * TABSIZE.  All following lines -- these are
    the reflowed lines generated by this function -- start at the same
    column as the first character beyond the opening { in the first
    line.
    """
    size = MAX_COL - depth * TABSIZE
    if len(s) < size:
        return [s]

    lines = []
    cur = s
    padding = ""
    while len(cur) > size:
        i = cur.rfind(' ', 0, size)
        # XXX this should be fixed for real
        if i == -1 and 'GeneratorExp' in cur:
            i = size + 3
        assert i != -1, "Impossible line %d to reflow: %r" % (size, s)
        lines.append(padding + cur[:i])
        if len(lines) == 1:
            # find new size based on brace
            j = cur.find('{', 0, i)
            if j >= 0:
                j += 2 # account for the brace and the space after it
                size -= j
                padding = " " * j
            else:
                j = cur.find('(', 0, i)
                if j >= 0:
                    j += 1 # account for the paren (no space after it)
                    size -= j
                    padding = " " * j
        cur = cur[i+1:]
    else:
        lines.append(padding + cur)
    return lines

def reflow_c_string(s, depth):
    return '"%s"' % s.replace('\n', '\\n"\n%s"' % (' ' * depth * TABSIZE))


def is_simple(sum_type):
    """Return True if a sum is simple.

    A sum is simple if its types have no fields and the sum itself
    has no attributes. The sum type is mapped to an enum in Java.
    Instances are the values of the enum and are singletons when
    propagated to the Python level in the _ast module, e.g.
    unaryop = Invert | Not | UAdd | USub
    """

    return not (
        sum_type.attributes or
        any(constructor.fields for constructor in sum_type.types)
    )


def asdl_of(name, obj):
    if isinstance(obj, asdl.Product) or isinstance(obj, asdl.Constructor):
        fields = ", ".join(map(str, obj.fields))
        if fields:
            fields = "({})".format(fields)
        return "{}{}".format(name, fields)
    else:
        if is_simple(obj):
            types = " | ".join(type.name for type in obj.types)
        else:
            sep = "\n{}| ".format(" " * (len(name) + 1))
            types = sep.join(
                asdl_of(type.name, type) for type in obj.types
            )
        return "{} = {}".format(name, types)


class EmitVisitor(asdl.VisitorBase):
    """Visit that emits lines"""

    def __init__(self, file, metadata = None):
        self.file = file
        self._metadata = metadata
        super(EmitVisitor, self).__init__()

    def emit(self, s, depth, reflow=True):
        # XXX reflow long lines?
        if reflow:
            lines = reflow_lines(s, depth)
        else:
            lines = [s]
        for line in lines:
            if line:
                line = (" " * TABSIZE * depth) + line
            self.file.write(line + "\n")

    @property
    def metadata(self):
        if self._metadata is None:
            raise ValueError(
                "%s was expecting to be annnotated with metadata"
                % type(self).__name__
            )
        return self._metadata

    @metadata.setter
    def metadata(self, value):
        self._metadata = value



class MetadataVisitor(asdl.VisitorBase):
    ROOT_TYPE = "AST"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Metadata:
        #    - simple_sums: Tracks the list of compound type
        #                   names where all the constructors
        #                   belonging to that type lack of any
        #                   fields.
        #    - identifiers: All identifiers used in the AST declarations
        #    - singletons:  List of all constructors that originates from
        #                   simple sums.
        #    - types:       List of all top level type names
        #
        self.metadata = types.SimpleNamespace(
            simple_sums=set(),
            identifiers=set(),
            singletons=set(),
            types={self.ROOT_TYPE},
        )

    def visitModule(self, mod):
        for dfn in mod.dfns:
            self.visit(dfn)

    def visitType(self, type):
        self.visit(type.value, type.name)

    def visitSum(self, sum, name):
        self.metadata.types.add(name)

        simple_sum = is_simple(sum)
        if simple_sum:
            self.metadata.simple_sums.add(name)

        for constructor in sum.types:
            if simple_sum:
                self.metadata.singletons.add(constructor.name)
            self.visitConstructor(constructor)
        self.visitFields(sum.attributes)

    def visitConstructor(self, constructor):
        self.metadata.types.add(constructor.name)
        self.visitFields(constructor.fields)

    def visitProduct(self, product, name):
        self.metadata.types.add(name)
        self.visitFields(product.attributes)
        self.visitFields(product.fields)

    def visitFields(self, fields):
        for field in fields:
            self.visitField(field)

    def visitField(self, field):
        self.metadata.identifiers.add(field.name)



class NamingVisitor(asdl.VisitorBase):
    """
    Visitor to survey the names used in AST elements in C and Java.

    We survey the types defined (and constructor names), to
    ensure we encounter them before the fields or attributes that
    may use these types.
    """

    # ASDL's 4 built in types are: identifier, string, int, and constant
    _ASDL_JAVA_TYPE = dict(
        identifier='String',
        string='String',
        int='int',
        constant='Object',
    )
    assert set(_ASDL_JAVA_TYPE.keys()) == set(asdl.builtin_types)

    def __init__(self, context: AsdlJavaContext):
        super().__init__()
        self.context = context
        # Map name in Python.asdl to Java type (primitive, class or enum)
        self.asdl_map = context.asdl_java_map = dict(NamingVisitor._ASDL_JAVA_TYPE)
        # Translation helpers from CPython to Java (e.g. in actions):
        # Map typedef to type (class or enum reference)
        self.type_map: dict[str, str] = dict()
        # Map constant to enum constant (e.g. X->MyEnum.X)
        self.constant_map: dict[str, str] = dict()
        # Map function call to method or constructor call (e.g. _PyAST_X->MyEnum.X)
        self.call_map: dict[str, str] = dict()

    def add_asdl(self, asdl_name: str, java_name: str):
        self.asdl_map[asdl_name] = java_name

    def add_type(self, c_name: str, java_name: str):
        self.type_map[c_name] = java_name

    def add_constant(self, c_name: str, java_name: str):
        self.constant_map[c_name] = java_name

    def add_call(self, c_name: str, java_name: str):
        self.call_map[c_name] = java_name

    def visitModule(self, mod: asdl.Module):
        for dfn in mod.dfns:
            self.visit(dfn)

    def visitType(self, t: asdl.Type):
        self.visit(t.value, t.name)

    def visitSum(self, sum: asdl.Sum, name: str):
        if is_enum := is_simple(sum):
            # The sum is represented by an enum. "Constructors" are constants.
            java_name = to_java_name(name, prefix='_', start_with_upper=True)
        else:
            # The sum is represented by an abstract class.
            java_name = to_java_name(name, prefix='AST', start_with_upper=True)
        self.add_asdl(name, java_name)
        # CPython has a corresponding type name_ty
        self.add_type(f'{name}_ty', java_name)
        # Find the names of concrete sub-types or enum constants.
        for cons in sum.types:
            self.visit(cons, is_enum, java_name)

    def visitConstructor(self, cons: asdl.Constructor, is_enum: bool, qualifier: str):
        name = cons.name
        java_name = to_java_name(name)
        # TODO Java class (c|sh)ould be nested and name qualified
        self.add_asdl(name, java_name)
        if is_enum:
            # CPython has an enum constant called name, that in Java
            # is also an enum constant scoped by the qualifier.
            self.add_constant(name, f'{qualifier}.{java_name}')
        else:
            # CPython has a factory _PyAST_name returning name_ty,
            # that in Java becomes a constructor call.
            self.add_call(f'_PyAST_{name}', f'new {java_name}')

    def visitProduct(self, product: asdl.Product, name: str):
        # A product is represented by a concrete (non-nested) class
        java_name = to_java_name(name, start_with_upper=True)
        self.add_asdl(name, java_name)
        # CPython has a corresponding type name_ty
        self.add_type(f'{name}_ty', java_name)
        # CPython has a factory returning name_ty called:
        self.add_call(f'_PyAST_{name}', f'new {java_name}')



class StructVisitor(asdl.VisitorBase):
    """
    Visitor to generate classes and enums for the AST.

    This relies on a mapping of the names of ASDL types to Java,
    that has been stored in the context object by a NamingVisitor.
    """

    def __init__(self, context: AsdlJavaContext):
        super().__init__()
        self.context = context
        self.package = context.ast_package
        self.cls_stack = [context.base_type]
        self.default_visitor = JavaVisitor("ASTDefaultVisitor", base_cls=None,
                                           package=self.package, modifiers=['public'])
        self.visitor_stack = [(self.cls_stack[0], self.default_visitor)]
        self.java_classes = [self.default_visitor]

    def write_java_classes(self):
        """
        Writes all generated Java-classes to disk.
        """
        ctx = self.context
        path = ctx.get_package_path()
        generator = ctx.generator
        for jc in self.java_classes:
            jc.save_to_file(path, generator)

    def begin_class(self, name: str,
                    cls_type: Callable[..., JavaClass] = JavaClass,
                    create_visitor: bool = False):
        base_cls = self.cls_stack[-1]
        cls = cls_type(name, base_cls=base_cls, package=self.package, modifiers=['public'])
        self.cls_stack.append(cls)
        self.java_classes.append(cls)
        if cls.visitable:
            for (_, visitor) in self.visitor_stack:
                visitor.add_visit_method(cls)
        if create_visitor:
            iface = JavaVisitorInterface(name + 'Visitor',
                                         package=self.package)
            self.visitor_stack.append((cls, iface))
            self.java_classes.append(iface)
            # The default visitor implements this interface too
            self.default_visitor.add_interface(iface)
        return cls

    def end_class(self):
        cls = self.cls_stack.pop()
        if self.visitor_stack and self.visitor_stack[-1][0] == cls:
            self.visitor_stack.pop()

    def get_java_type(self, asdl_type_name: str, is_seq: bool = False) -> str:
        """Map an ASDL type to its Java type"""
        if is_seq:
            return self.get_java_type(asdl_type_name) + '[]'  # or PyList ?
        return self.context.asdl_java_map[asdl_type_name]

    @property
    def current_class(self):
        return self.cls_stack[-1]

    def visitModule(self, mod):
        for dfn in mod.dfns:
            self.visit(dfn)

    def visitType(self, type):
        self.visit(type.value, type.name)

    def visitSum(self, sum, asdl_name):
        if is_simple(sum):
            self.sum_as_enum(sum, asdl_name)
        else:
            self.sum_with_constructors(sum, asdl_name)

    def sum_as_enum(self, sum, asdl_name):
        java_name = self.get_java_type(asdl_name)
        cls = self.begin_class(java_name, JavaPseudoEnum)
        for field in sum.types:
            cls.add(field.name)
        self.end_class()

    def sum_with_constructors(self, sum, asdl_name):
        java_name = self.get_java_type(asdl_name)
        cls = self.begin_class(java_name, JavaClass, True)
        for field in sum.attributes:
            type = self.get_java_type(field.type)
            init = default_value_for_j_type(type)
            cls.add(JavaVariable(field.name, type, init))
        for t in sum.types:
            self.visit(t)
        self.end_class()

    def visitConstructor(self, cons):
        cls = self.begin_class(self.get_java_type(cons.name))
        for field in cons.fields:
            self.visit(field)
        self.end_class()

    def visitField(self, field):
        java_type = self.get_java_type(field.type, field.seq)
        self.current_class.add(
            JavaVariable(field.name, java_type, is_optional=field.opt))

    def visitProduct(self, product, asdl_name):
        cls = self.begin_class(self.get_java_type(asdl_name))
        for field in product.fields:
            self.visit(field)
        for field in product.attributes:
            # rudimentary attribute handling
            type = self.get_java_type(field.type)
            assert type in asdl.builtin_types, type
            cls.add(JavaVariable(field.name, type))
        self.end_class()

def write_source(context: AsdlJavaContext, mod):
    v = StructVisitor(context)
    v.visit(mod)
    v.write_java_classes()
    print("Output written to", context.get_package_path())


def main(context: AsdlJavaContext, input_file: str, dump_module=False):
    # TODO Avoid use of global state. Possibly avoid this cache.
    #set_cache_file_path(context.c_java_map)

    # Build an AST of the ASDL that describes the AST of the language.
    mod = asdl.parse(input_file)
    if dump_module:
        print('Parsed Module:')
        print(mod)
    if not asdl.check(mod):
        sys.exit(1)

    # Preserved from asdl_c.py so we can see what it does
    metadata_visitor = MetadataVisitor()
    metadata_visitor.visit(mod)
    metadata = metadata_visitor.metadata


    # Gather the names of data types and their translations to Java.
    # We do this before we encounter them as field types.
    names = NamingVisitor(context)
    names.visit(mod)

    # Write java_type_converter global dictionary with C->Java map.
    # TODO Avoid use of this cache as global
    with open(context.c_java_map, 'wt', encoding='utf-8', newline='\n') as cache:
        for m in (names.type_map, names.constant_map, names.call_map):
            for c_expr, java_expr in m.items():
                cache.write(f"{c_expr}->{java_expr}\n")

    # Walk the tree generating Java classes for the types it defines.
    # These are the AST classes we use in the parser.
    write_source(context, mod)


if __name__ == "__main__":
    prog_dir = Path(__file__).parent
    parser = ArgumentParser()
    parser.add_argument("input_file", type=Path, nargs='?',
                        default=Path(__file__).with_name('Python.asdl'),
                        help="ASDL defining the nodes (default: built-in Python.asdl)")
    parser.add_argument("output_dir", type=Path, nargs='?',
                        default=Path.cwd().joinpath(*OUTPUT_DIR.split('/')),
                        help=f"output directory for generated code (default: {OUTPUT_DIR})")
    parser.add_argument("-a", "--ast-package", default=AST_PACKAGE,
                        help=f"AST Java package name (default: {AST_PACKAGE})")
    parser.add_argument("-b", "--base-type",
                        default=BASE_TYPE,
                        help=f"Base class name in AST package (default: {BASE_TYPE})")
    parser.add_argument("-c", "--core-package",
                        default=CORE_PACKAGE,
                        help=f"Core Jython package name (default: {CORE_PACKAGE})")
    # TODO Add option to read mapping(s). Probably always write mappings.
    parser.add_argument("-m", "--c-java-map", type=Path,
                        default=None,
                        help=f"C-Java map to write (default: <output_dir>/.c_java_map)")
    parser.add_argument("-d", "--dump-module", action="store_true")

    args = parser.parse_args()

    if args.c_java_map is None:
        args.c_java_map = args.output_dir / '.c_java_map'

    main(AsdlJavaContext(
            args.output_dir,
            args.core_package,
            args.ast_package,
            args.base_type,
            args.c_java_map,
            __file__
        ),
        args.input_file,
        args.dump_module)
